title:              Machine Learning Projects
email:              hounnou2@illinois.edu
description:        A Blog Theme by Start Bootstrap
author:             Leon Hounnou
baseurl:            ""
url:                "https://Hounnou.github.io"

# Social Profiles
twitter_username:   
github_username:    Hounnou
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
